import java.awt.Color;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.*;
import java.text.MessageFormat;
import javax.swing.*;
import java.util.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.AbstractTableModel;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author skYlark
 */
public class Clinical_Trials extends javax.swing.JInternalFrame {

     Connection conn=null;
ResultSet rs = null;
PreparedStatement pst=null;
String sql=null;
    public Clinical_Trials() throws SQLException {
        initComponents();
        Show_Users_In_JTable();
    }
     public ArrayList<user4> getUserList() throws SQLException
    {
        conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/biotechinfo?autoReconnect=true&useSSL=false","root","root"); 
        ArrayList<user4> usersList = new ArrayList<user4>();
        String searchQuery = "SELECT * FROM clinical_trials"; 
        Statement st;
        ResultSet rs;
        
        try{
            st = conn.createStatement();
           
            rs=st.executeQuery(searchQuery);
            
            user4 User;
            
            while(rs.next())
            {
                User = new user4(
                                rs.getInt("Trial_Id"), 
                                rs.getInt("Trial_Site_Id"),
                                 rs.getInt("Dept_Id"),
                                 rs.getDate("Trial_Date"),
                                 rs.getString("Trial_Title")
                                );
                usersList.add(User);
            }
            
        }catch(Exception ex){
            //System.out.println(ex.getMessage());
            ex.printStackTrace();
        }
        
        return usersList;
    }
 
      
   public void Show_Users_In_JTable() throws SQLException
    {
        ArrayList<user4> users = getUserList();
        DefaultTableModel model = new DefaultTableModel();
        model = (DefaultTableModel)jtable4.getModel();
        //model.setColumnIdentifiers(new Object[]{"Dept_Id","Hospital_Id","Dept_Name","Contact","Email"});
        Object[] row = new Object[5];
        
        for(int i = 0; i < users.size(); i++)
        {
            row[0] = users.get(i).getId();
            row[1] = users.get(i).getId2();
            row[2] = users.get(i).getid3();
            row[3] = users.get(i).getdate();
            row[4] = users.get(i).gettitle();
            model.addRow(row);
        }
       jtable4.setModel(model);
       
    }
   public void executeSQlQuery(String query, String message) throws SQLException
   {
        conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/biotechinfo?autoReconnect=true&useSSL=false","root","root");
       Statement st;
       try{
           st = conn.createStatement();
           if((st.executeUpdate(query)) == 1)
           {
               // refresh jtable data
               DefaultTableModel model = (DefaultTableModel)jtable4.getModel();
               model.setRowCount(0);
               Show_Users_In_JTable();
               
               JOptionPane.showMessageDialog(null, "Data "+message+" Succefully");
           }else{
               JOptionPane.showMessageDialog(null, "Data Not "+message);
           }
       }catch(Exception ex){
           ex.printStackTrace();
       }
   }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        search = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        id1 = new javax.swing.JTextField();
        id2 = new javax.swing.JTextField();
        id3 = new javax.swing.JTextField();
        date = new javax.swing.JTextField();
        title = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtable4 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 51, 204));
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Clinical Trials");

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 0));
        jLabel1.setText("Details");

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 8)); // NOI18N
        jButton2.setForeground(new java.awt.Color(153, 0, 0));
        jButton2.setIcon(new javax.swing.ImageIcon("F:\\DBMS\\1-11-18\\2_GUI development Tutorial_FrontEnd_BackEnd\\must_have_icons_icons_pack_120704\\Search\\Search_16x16.png")); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 0, 0));
        jLabel2.setText("Trial Id");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 0, 0));
        jLabel3.setText("Trial Site Id");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 0, 0));
        jLabel4.setText("Department Id");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 0, 0));
        jLabel5.setText("Trial Date");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 0, 0));
        jLabel6.setText("Trial Title");

        title.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                titleActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 8)); // NOI18N
        jButton3.setForeground(new java.awt.Color(153, 0, 0));
        jButton3.setIcon(new javax.swing.ImageIcon("F:\\DBMS\\1-11-18\\2_GUI development Tutorial_FrontEnd_BackEnd\\must_have_icons_icons_pack_120704\\Delete\\Delete_16x16.png")); // NOI18N
        jButton3.setText("Delete");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 8)); // NOI18N
        jButton4.setForeground(new java.awt.Color(153, 0, 0));
        jButton4.setIcon(new javax.swing.ImageIcon("F:\\DBMS\\1-11-18\\2_GUI development Tutorial_FrontEnd_BackEnd\\must_have_icons_icons_pack_120704\\Edit\\Edit_16x16.png")); // NOI18N
        jButton4.setText("Update");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 8)); // NOI18N
        jButton6.setForeground(new java.awt.Color(153, 0, 0));
        jButton6.setIcon(new javax.swing.ImageIcon("F:\\DBMS\\1-11-18\\2_GUI development Tutorial_FrontEnd_BackEnd\\must_have_icons_icons_pack_120704\\Add\\Add_16x16.png")); // NOI18N
        jButton6.setText("Insert");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel2))
                                .addGap(29, 29, 29)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(date, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE)
                                    .addComponent(title)
                                    .addComponent(id2)
                                    .addComponent(id3)
                                    .addComponent(id1)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton2))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(jButton6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4)))
                .addContainerGap(77, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(search))
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(id1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(id2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(id3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton3)
                        .addComponent(jButton4))
                    .addComponent(jButton6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jtable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Trial_Id", "Trial_Site_Id", "Dept_Id", "Trial_Date", "Trial_Title"
            }
        ));
        jtable4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtable4MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtable4);

        jButton1.setForeground(new java.awt.Color(153, 0, 0));
        jButton1.setText("Exit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 8)); // NOI18N
        jButton5.setForeground(new java.awt.Color(153, 0, 0));
        jButton5.setIcon(new javax.swing.ImageIcon("F:\\DBMS\\1-11-18\\2_GUI development Tutorial_FrontEnd_BackEnd\\must_have_icons_icons_pack_120704\\Refresh\\Refresh_16x16.png")); // NOI18N
        jButton5.setText("Refresh");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 382, Short.MAX_VALUE)
                .addGap(2, 2, 2))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jButton5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton5))
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(2, 2, 2))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void titleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_titleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_titleActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       try{
           int i=-1;
           i = jtable4.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel)jtable4.getModel();
        if(i >= 0 )
        {
            model.setValueAt(id1.getText(), i, 0);
            model.setValueAt(id2.getText(), i, 1);
            model.setValueAt(id3.getText(), i, 2);
            model.setValueAt(date.getText(), i, 3);
            model.setValueAt(title.getText(), i, 4);
            String value=id1.getText();
            String value0=id2.getText();
           String value1=id3.getText();
            String value2=date.getText();
           String value3=title.getText();
           String sql="update clinical_trials set Trial_Site_Id='"+value0+"',Dept_Id='"+value1+"',Trial_Date='"+value2+"',Trial_Title='"+value3+"'where Trial_Id ="+value+""; 
            pst =conn.prepareStatement(sql);
           pst.execute();
            JOptionPane.showMessageDialog(null, "Updated");
        }else{
            String value=id1.getText();
       String value0=id2.getText();
       String value1=id3.getText();
       String value2=date.getText();
       String value3=title.getText();
       String sql="update clinical_trials set Trial_Site_Id='"+value0+"',Dept_Id='"+value1+"',Trial_Date='"+value2+"',Trial_Title='"+value3+"'where Trial_Id ="+value+"";
       pst =conn.prepareStatement(sql);
       pst.execute();
       JOptionPane.showMessageDialog(null, "Updated"); 
        }
      
       }
           catch(Exception e)
    {
           JOptionPane.showMessageDialog(null, e);
    } 
    
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       try{
                 
    String sql="select * from clinical_trials where Trial_Id=? ";
    pst =conn.prepareStatement(sql);
   pst.setString(1,search.getText());
  

    rs=pst.executeQuery();
   // pst.execute();
   if(rs.next()){
       String add=rs.getString("Trial_Id");
    id1.setText(add);
    String add5=rs.getString("Trial_Site_Id");
    id2.setText(add5);
    String add1=rs.getString("Dept_Id");
    id3.setText(add1);
    String add2=rs.getString("Trial_Title");
   date.setText(add2);
   String add3=rs.getString("Trial_Title");
     title.setText(add3);
      }  

   }
   
           catch(Exception e)
    {
           JOptionPane.showMessageDialog(null, e);

    }
         try{
                 
    String sql="select * from clinical_trials where Trial_Site_Id=? ";
    pst =conn.prepareStatement(sql);
   pst.setString(1,search.getText());
  

    rs=pst.executeQuery();
   // pst.execute();
   if(rs.next()){
     String add=rs.getString("Trial_Id");
    id1.setText(add);
    String add5=rs.getString("Trial_Site_Id");
    id2.setText(add5);
    String add1=rs.getString("Dept_Id");
    id3.setText(add1);
    String add2=rs.getString("Trial_Title");
   date.setText(add2);
   String add3=rs.getString("Trial_Title");
     title.setText(add3);
      }  
   }
   
           catch(Exception e)
    {
           JOptionPane.showMessageDialog(null, e);

    }
           try{
                 
     String sql="select * from clinical_trials where Dept_Id=? ";
    pst =conn.prepareStatement(sql);
   pst.setString(1,search.getText());
  

    rs=pst.executeQuery();
   // pst.execute();
   if(rs.next()){
     String add=rs.getString("Trial_Id");
    id1.setText(add);
    String add5=rs.getString("Trial_Site_Id");
    id2.setText(add5);
    String add1=rs.getString("Dept_Id");
    id3.setText(add1);
    String add2=rs.getString("Trial_Title");
   date.setText(add2);
   String add3=rs.getString("Trial_Title");
     title.setText(add3);
      }  
   }
   
           catch(Exception e)
    {
           JOptionPane.showMessageDialog(null, e);

    }
                try{
                 
     String sql="select * from clinical_trials where Trial_Date=? ";
    pst =conn.prepareStatement(sql);
   pst.setString(1,search.getText());
  

    rs=pst.executeQuery();
   // pst.execute();
   if(rs.next()){
       String add=rs.getString("Trial_Id");
    id1.setText(add);
    String add5=rs.getString("Trial_Site_Id");
    id2.setText(add5);
    String add1=rs.getString("Dept_Id");
    id3.setText(add1);
    String add2=rs.getString("Trial_Title");
   date.setText(add2);
   String add3=rs.getString("Trial_Title");
     title.setText(add3);
      }  
   }
   
           catch(Exception e)
    {
           JOptionPane.showMessageDialog(null, e);

    }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
       conn= Mysqlconnection.ConnectDB();
      String sql="Insert into clinical_trials(Trial_Id,Trial_Site_Id,Dept_Id,Trial_Date,Trial_Title) value (?,?,?,?,?)";
       try
       {
         
            pst=conn.prepareStatement(sql);
           pst.setString(1,id1.getText());
          pst.setString(2,id2.getText());
              pst.setString(3,id3.getText());
              pst.setString(4,date.getText());
              pst.setString(5,title.getText());
              
               
                 
                pst.execute();
                 
                 JOptionPane.showMessageDialog(null, "Data Inserted");
       
       }
       catch(Exception e)
       {
         
            JOptionPane.showMessageDialog(null, "Failed");
           
       }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        
        String sql="delete from clinical_trials where Trial_Id=?";
        try{
            int i=-1;
        i = jtable4.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel)jtable4.getModel();
        if (i>=0){
            pst =conn.prepareStatement(sql);
            pst.setString(1, id1.getText());
    
    //rs=pst.executeQuery();
        executeSQlQuery(sql, "Deleted");
        pst.execute();
    
       JOptionPane.showMessageDialog(null, "Deleted");
        }
        else{
              pst =conn.prepareStatement(sql);
        pst.setString(1, id1.getText());
    
    //rs=pst.executeQuery();
        executeSQlQuery(sql, "Deleted");
        pst.execute();
    
       JOptionPane.showMessageDialog(null, "Deleted");
        }
      
    //QueryJFrame s = new QueryJFrame();
    //s.setVisible(true);
    
    
    
    
            
    }catch(Exception e)
    {
           JOptionPane.showMessageDialog(null, e);

    }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
       search.setText("");
       id1.setText("");
       id2.setText("");
       
        id3.setText("");
        date.setText("");
        title.setText("");
        DefaultTableModel model = (DefaultTableModel)jtable4.getModel();
        model.setRowCount(0);
         try {
             Show_Users_In_JTable();
         } catch (SQLException ex) {
             Logger.getLogger(Department.class.getName()).log(Level.SEVERE, null, ex);
         }
         
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jtable4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtable4MouseClicked
      int i = jtable4.getSelectedRow();
        
         // get the model from the jtable
       DefaultTableModel model = (DefaultTableModel)jtable4.getModel();
       
      //  Show_Users_In_JTable();

      
        model = (DefaultTableModel) jtable4.getModel();
        
         //Display Slected Row In JTexteFields
       id1.setText(model.getValueAt(i,0).toString());

        id2.setText(model.getValueAt(i,1).toString());

        id3.setText(model.getValueAt(i,2).toString());

        date.setText(model.getValueAt(i,3).toString());  
        title.setText(model.getValueAt(i,4).toString());         
    }//GEN-LAST:event_jtable4MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField date;
    private javax.swing.JTextField id1;
    private javax.swing.JTextField id2;
    private javax.swing.JTextField id3;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtable4;
    private javax.swing.JTextField search;
    private javax.swing.JTextField title;
    // End of variables declaration//GEN-END:variables
}
